[window]
opacity = 0.96
dynamic_padding = true
decorations = "None"
blur = true
startup_mode = "Maximized"

[cursor.style]
shape = "Beam"

[font.normal]
family = "DejaVuSansM Nerd Font Mono" 
style = "Regular"
